#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'learning-tf2-py==0.0.0','console_scripts','turtle_tf2_message_broadcaster'
__requires__ = 'learning-tf2-py==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('learning-tf2-py==0.0.0', 'console_scripts', 'turtle_tf2_message_broadcaster')()
    )
